version: '3.9'
services:
  api:
    image: 'antonmakarenko/random-quotes-api:1.0.0'
    ports:
      - '8080:8080'

  downloader:
    image: 'antonmakarenko/random-quotes-downloader:1.0.0'
    ports:
      - '8081:8081'

  data:
    image: 'antonmakarenko/random-quotes-data:14.4'
    ports:
      - '5432:5432'
#    volumes:
#      - 'E:/Docker/random-quotes/postgresql/data:/var/lib/postgresql/data'